### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by mgjm** [wirvsvirus-teamx/grenzexpress#19]
Folgend Routen:
```
GET    /blob/{publicKey}
PUT    /blob/{publicKey}
DELETE /blob/{publicKey}
```

Jeder gespeicherte Blob besitzt ein Public / Private Key (Ed25519).
Der Public Key wird `base64url` encoded (ohne Padding) nach [RFC 4648 - Section 5](https://tools.ietf.org/html/rfc4648#section-5) als ID in den URLs verwendet.

`PUT` und `DELETE` Anfragen müssen mit einer Signatur des Private Key autorisiert werden. Dazu wird der neue Payload des Blob per Ed25519 ([RFC 8032](https://tools.ietf.org/html/rfc8032)) signiert und die Signatur `base64` ([RFC 4648 - Section 4](https://tools.ietf.org/html/rfc4648#section-4)) im `Authorization` header übermittelt:
```
Authorization: signature <base64-signature-data>
```

Bei `DELETE` Anfragen wird eine leere Bytesequenz signiert. Entsprechend muss eine leere `PUT` Anfrage mit einem Fehler oder als implizites `DELETE` behandelt werden.

Zusätzlich wird das eigentliche Payload noch symmetrisch verschlüsselt. Dazu wird ein 256 Bit Zufallskey erstellt. Mit diesem kann dann `AEAD_CHACHA20_POLY1305`Verschlüsselung auf dem Client ausgeführt werden ([RFC 7539](https://tools.ietf.org/html/rfc7539)).

Wichtig ist, dass weder der Private Schlüssel noch der symmetrische Schlüssel auf dem Server verarbeitet werden darf. Insbesondere muss auch darauf geachtet werden, dass er z.B. nicht in (serverseitigen) URLs auftaucht.
```diff
- https://example.com/?priv=<privateKey>&key=<symmetricKey>
+ https://example.com/#priv=<privateKey>&key=<symmetricKey>
                      ^
```

**Comment by riesinger** [comment]
> Bei DELETE Anfragen wird eine leere Bytesequenz signiert. Entsprechend muss eine leere PUT Anfrage mit einem Fehler oder als implizites DELETE behandelt werden.

Um das möglichst sauber zu machen würde ich sagen, dass ein leeres `PUT` ein Fehler ist

**Comment by riesinger** [comment]
Irgendwie bräuchten wir noch ein `POST`, um Formulare erstmalig anzulegen... Oder wir nehmen einfach ein `PUT` tun einfach so, als ob es für den Key schon Daten gibt

@mgjm Meinungen Dazu?

**Comment by mgjm** [comment]
@riesinger Einen `POST` bräuchten wir nur, wenn der Server die neue Location bestimmen würde... also sowas wie `POST /blob`. Bei uns kann aber einfach ein `PUT /blob/{publicKey}` verwendet werden, um einen neuen Blob abzulegen.

**Comment by riesinger** [comment]
Ja, stimmt eigentlich 👍 dann baue ich das so

**Comment by riesinger** [comment]
Kann das hier geschlossen werden? Die API ist ja umgesetzt.

Den Issue-Text würde ich aber auf jeden Fall mit in die Dokumentation übernehmen

**Comment by mgjm** [comment]
Ich würde es noch offen lassen, bis auch das Frontend die API umgesetzt hat.
